### ISSUE TITLE
Macbook Pro 2016

### ISSUE THREAD

**Issue by purevertigo** [tobiasthyssen/pocket-casts-media-controls#2]
Doesn't work with Touchbar Mac

**Comment by tobiasthyssen** [comment]
I do not own a mac with a touchbar myself, so i have hard time testing this. 

I'm thinking it could be a problem with chrome mapping the media keys wrong. Could you try going to Settings -> Extensions, scroll to the bottom and open keyboard shortcuts. Then change the shortcut to the touchbar media keys?

**Comment by purevertigo** [comment]
No. Sorry doesn't work either.

**Comment by tobiasthyssen** [comment]
You can always use a different shortcut. For example I use `alt+q/w/e`.

**Comment by tobiasthyssen** [comment]
Thank you for testing.

I can't seem to find anything about this, and because I don't own a macbook myself, I can't really fix this reliably. You're welcome to take a stab at it if you like :smile: 

You can always use a different shortcut. For example I use `Alt + q/w/e`.
